/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jbadams.hibernate;
import org.jbadams.hibernate.jdbc.TestJdbc;
import org.jbadams.hibernate.one_to_one_bi.script.GetInstructorDetail;
import org.jbadams.hibernate.one_to_one_bi.script.DeleteInstructorDetail;
import org.jbadams.hibernate.demo.CreateStudentDemo;
import org.jbadams.hibernate.demo.PrimaryKeyDemo;
import org.jbadams.hibernate.demo.ReadStudentDemo;
import org.jbadams.hibernate.demo.QueryStudentDemo;
import org.jbadams.hibernate.demo.UpdateStudentDemo;
import org.jbadams.hibernate.demo.DeleteStudentDemo;
import org.jbadams.hibernate.activity.scripts.CreateEmployee;
import org.jbadams.hibernate.activity.scripts.GetEmployee;
import org.jbadams.hibernate.activity.scripts.QueryEmployee;
import org.jbadams.hibernate.activity.scripts.DeleteEmployee;
import org.jbadams.hibernate.one_to_one_uni.test.TestJdbcOneToOneUni;
import org.jbadams.hibernate.one_to_one_uni.script.CreateInstructor;
import org.jbadams.hibernate.one_to_one_uni.script.DeleteInstructor;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        
        if (args[0].equals("TestJdbc")) {
            TestJdbc.run(args);
        } else if (args[0].equals("CreateStudentDemo")) {
            CreateStudentDemo.run(args);
        } else if (args[0].equals("PrimaryKeyDemo")) {
            PrimaryKeyDemo.run(args);
        } else if (args[0].equals("ReadStudentDemo")) {
            ReadStudentDemo.run(args);
        } else if (args[0].equals("QueryStudentDemo")) {
            QueryStudentDemo.run(args);
        } else if (args[0].equals("UpdateStudentDemo")) {
            UpdateStudentDemo.run(args);
        } else if (args[0].equals("DeleteStudentDemo")) {
            DeleteStudentDemo.run(args);
        } else if (args[0].equals("CreateEmployee")) {
            CreateEmployee.run(args);
        } else if (args[0].equals("GetEmployee")) {
            GetEmployee.run(args);
        } else if (args[0].equals("QueryEmployee")) {
            QueryEmployee.run(args);
        } else if (args[0].equals("DeleteEmployee")) {
            DeleteEmployee.run(args);
        } else if (args[0].equals("TestJdbcOneToOneUni")) {
            TestJdbcOneToOneUni.run(args);
        } else if (args[0].equals("CreateInstructor")) {
            CreateInstructor.run(args);
        } else if (args[0].equals("DeleteInstructor")) {
            DeleteInstructor.run(args);
        } else if (args[0].equals("GetInstructorDetail")) {
            GetInstructorDetail.run(args);
        } else if (args[0].equals("DeleteInstructorDetail")) {
            DeleteInstructorDetail.run(args);
        } else {
            System.out.println("No Flag Provided");
        }
    }
}
